language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - sudo apt-get update
  - sudo apt-get install libdmtx-dev libdmtx-utils
  - pip install .
  - pip install -r requirements.txt

script: python -m unittest discover
